### ISSUE TITLE
inline edit content

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#273]
enable inline editing in the page view

current work can be found at https://github.com/headwirecom/peregrine-cms/tree/feature/inlineedit

to enable inline edit on a component the component needs to use the attribute data-per-inline-edit="model.text" on the html element where inline editing should be enabled

current issues:
- should use the same editor as the dialog editor
- need to figure out where to place the styling features (bold, italic, etc)
- some css issues

**Comment by flx-sta** [comment]
@reusr1 small gifs to present the feature would be helpful (my opinion)

**Comment by flx-sta** [comment]
@reusr1 please add the checklist we discussed

**Comment by reusr1** [comment]
- make sure the selection of a component can be done programmatically using actions
- establish an inline edit state for the contentview
- use the contenteditable approach (body contenteditable, wrapper-div contenteditable=false, element to edit in component: contenteditable=true
- track movement of selection range between components and show correct right hand rail based on the component
- start inline editing when clicking on an area that is inline editable
- make sure the right rail shows the current field that is edited

note: 
html that support inline editing have a data-per-inline attribute like 'model.text' or if from a list 'model.field.#number.text' 

@Felix-Puetz I hope this list is somewhat complete

**Comment by flx-sta** [comment]
- make sure the selection of a component can be done programmatically using actions
establish an inline edit state for the contentview ✔️ 
- use the contenteditable approach (body contenteditable, wrapper-div contenteditable=false, element to edit in component: contenteditable=true✔️ 
- track movement of selection range between components and show correct right hand rail based on the component✔️ 
- start inline editing when clicking on an area that is inline editable✔️ 
- make sure the right rail shows the current field that is edited✔️

**Comment by reusr1** [comment]
@Felix-Puetz please also look at the following:
- autosave when moving from one component to another in inline edit mode
- themecleanflex cards not focusing on current field
- issues with deleting all text and starting to write text again
- ctrl-a (mac command-a) support to select the text in the current content editable
- generally try to edit a larger page with themecleanflex components
 
- support for move with cursor keys between content editable in firefox

**Comment by Felix-Puetz** [comment]
- autosave when moving from one component to another in inline edit mode ✅  
- themecleanflex cards not focusing on current field ✅ 
- issues with deleting all text and starting to write text again 🔲 
- ctrl-a (mac command-a) support to select the text in the current content editable 🔲 
- generally try to edit a larger page with themecleanflex components 🔲 
- support for move with cursor keys between content editable in firefox 🔲

**Comment by reusr1** [comment]
- in themecleanflex add the horizontal teaser (not the example one) to the page, enable the title and try to edit the content
- drag and drop reordering of components is not supported anymore

**Comment by Felix-Puetz** [comment]
- autosave when moving from one component to another in inline edit mode ✅  
- themecleanflex cards not focusing on current field ✅ 
- issues with deleting all text and starting to write text again 🔲 
- ctrl-a (mac command-a) support to select the text in the current content editable 🔲 
- generally try to edit a larger page with themecleanflex components 🔲 
- support for move with cursor keys between content editable in firefox 🔲 
- in themecleanflex add the horizontal teaser (not the example one) to the page, enable the title and try to edit the content 🔲 
- drag and drop reordering of components is not supported anymore 🔲

**Comment by flx-sta** [comment]
@reusr1 

> - generally try to edit a larger page with themecleanflex components ❗
>    - consider creating a follow-up issue. Probably caused by the fact that the contenteditable clones/original all have to be hidden/shown when the mouse enters/leaves the iframe-boundaries. I know this wasn't the best solutation but it was the best i could find to that time

**Comment by flx-sta** [comment]
- autosave when moving from one component to another in inline edit mode ✅  
- themecleanflex cards not focusing on current field ✅ 
  - (also for slow connections) ☑️ 
- issues with deleting all text and starting to write text again ✅ 
- ctrl-a (mac command-a) support to select the text in the current content editable ✅ 
- generally try to edit a larger page with themecleanflex components ☑️ 
  - _consider creating a follow-up issue. Probably caused by the fact that the contenteditable clones/original all have to be hidden/shown when the mouse enters/leaves the iframe-boundaries. I know this wasn't the best solutation but it was the best i could find to that time_
  - _I boosted the performance a bit by reducing the amount of removed & added elements on mouse-move_
- support for move with cursor keys between content editable in firefox ☑️ 
- in themecleanflex add the horizontal teaser (not the example one) to the page, enable the title and try to edit the content ✅ 
- drag and drop reordering of components is not supported anymore ✅ 
- newly added componen inline-edits are only `contenteditable` after moving the mouse out and in of the iframe ✅

**Comment by flx-sta** [comment]
@reusr1 anything else related to this specific issue (not any new features)

**Comment by reusr1** [comment]
- [x] all text deleted in a content editable does not delete the text in the right rail until you start typing (using select all and then backspace or delete)
- [x] when deleting text with select-all and backspace in a content editable undo does not work (just noting this here, we may have to look at a better undo/redo strategy for page editing to allow all content edits made on a page to be undoable)
- [x] cursor up at beginning of first editable or cursor down at the end of last editable throws javascript exception [1]
- [x] try adding the 'rich text' component in themecleanflex to the page, add some content to it, then use backspace to delete the content and add some content again - you should notice that the text is shown 2x in the editor [2]

[1] 
admin.js:4664 Uncaught TypeError: Cannot read property 'focus' of undefined
    at VueComponent.onInlineArrowKey (admin.js:4664)
    at VueComponent.onInlineKeyUp (admin.js:4602)

[2]
![image](https://user-images.githubusercontent.com/779992/81567615-65562580-9351-11ea-9d25-e03073ce203e.png)

**Comment by flx-sta** [comment]
> * when deleting text with select-all and backspace in a content editable undo does not work (just noting this here, we may have to look at a better undo/redo strategy for page editing to allow all content edits made on a page to be undoable)

I've tried certain approaches and as I see it the only 100% workable way would be to implemenet a history + undo + redo ourself.
This would take way too much time though...

I've made it partially available though. It just doesn't recover the content of the header after undo

**Comment by flx-sta** [comment]
> try adding the 'rich text' component in themecleanflex to the page, add some content to it, then use backspace to delete the content and add some content again - you should notice that the text is shown 2x in the editor [2]

I don't really have any idea how to overcome this issue.
This is caused by the conditional rendering of the inline-edit element. Since i create a clone from every inline-edit element to unhook the reactivity the clone is not influenced by the conditional rendering causing the clone to be re-created when the original is re-added conditionally.
My suggestion is to avoid behaviour like this for inline-edit elements. This would limit the "programming freedom" though. But on the other hand i have no clue how to handle this properly @reusr1

**Comment by reusr1** [comment]
> > try adding the 'rich text' component in themecleanflex to the page, add some content to it, then use backspace to delete the content and add some content again - you should notice that the text is shown 2x in the editor [2]
> 
> I don't really have any idea how to overcome this issue.
> This is caused by the conditional rendering of the inline-edit element. Since i create a clone from every inline-edit element to unhook the reactivity the clone is not influenced by the conditional rendering causing the clone to be re-created when the original is re-added conditionally.
> My suggestion is to avoid behaviour like this for inline-edit elements. This would limit the "programming freedom" though. But on the other hand i have no clue how to handle this properly @reusr1

@Felix-Puetz since there can only be one contenteditable at the given location in the dom it should be possible to at least test if we have a leftover contenteditable from before and remove that one when adding the new one

**Comment by flx-sta** [comment]
@reusr1 done, please verify

**Comment by reusr1** [comment]
@Felix-Puetz the duplication of content when clearing a content editable seems to be gone now, thank you

found another couple of issues: 

- [x] clicking on a component outside of the contenteditable are of the component does not select the component anymore
- ❌  I still see an issue with cursor direction up and cursor direction down skipping a component if the component has empty content editables
**Task moved to [new task list](https://github.com/headwirecom/peregrine-cms/issues/273#issuecomment-630219517)**

**Comment by flx-sta** [comment]
>  I still see an issue with cursor direction up and cursor direction down skipping a component if the component has empty content editables

~~Still not able to reproduce :/~~
**Was able to reproduce**

**Comment by flx-sta** [comment]
- [x] suddenly appearing gap if the newly selected component is out of screen

- [x]  empty inline-edits (e.g. jumbotrons) are skipped when using arrow-keys

- [x] Changes made on the right-panel are not reactive anyore since the clones only are displayed

- [x] `Ctrl` + `Shift` + `ARROW_KEY` does not support the default behaviour

- [x]  the javascript:void(0) seems to have issues while editing rich text components - the href of a elements does not get replaced back when saving components

- [x] fix having to double-down to be able to jump to next inline-edit

- [x] fix sudden jumps when moving with arrow keys over line-breaks

**Comment by reusr1** [comment]
- [ ] the javascript:void(0) seems to have issues while editing rich text components - the href of a elements does not get replaced back when saving components

**Comment by Felix-Puetz** [comment]
> Ctrl + Shift + ARROW_KEY does not support the default behaviour

Even if I disable the current `ARROW_KEY` event by adding `if (... && !event.shiftKey)` the behaviour is still present. It seems to be a defautl behaviour of the browser. I'd have to overwrite the default behaviour then
@reusr1 FYI

**Comment by reusr1** [comment]
> > Ctrl + Shift + ARROW_KEY does not support the default behaviour
> 
> Even if I disable the current `ARROW_KEY` event by adding `if (... && !event.shiftKey)` the behaviour is still present. It seems to be a default behaviour of the browser. I'd have to overwrite the default behaviour then
> @reusr1 FYI

@Felix-Puetz dont think so as this works fine on https://jsfiddle.net/d9fxos4y/1/

**Comment by reusr1** [comment]
@Felix-Puetz I think we should close this ticket but hold off on the merge until https://github.com/headwirecom/peregrine-cms/issues/381 is complete
